In [2]:
import numpy as np

In [ ]:
a = [1,2,4]

In [3]:
numpy_array = np.array([1, 2, 4])

In [4]:
numpy_array

array([1, 2, 4])

In [5]:
type(numpy_array)

numpy.ndarray

In [6]:
numpy_array[0]

np.int64(1)

In [7]:
test_array = np.array([[1,2,3]])
     

In [8]:
test_array

array([[1, 2, 3]])

In [9]:
test_array[0][0]

np.int64(1)

In [10]:

third_d_array = np.array([[[1,2,3], [4,5,6]]])

In [11]:

third_d_array.size

6

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [14]:

np.random.randint(2,10)

8

In [15]:

import pandas as pd

In [16]:
data_columns = {"students":[ "shyam", "ram", "hari"], "roll_no":[1, 4, 6]}

In [17]:
data_columns

{'students': ['shyam', 'ram', 'hari'], 'roll_no': [1, 4, 6]}

In [18]:
df = pd.DataFrame(data=data_columns)

In [19]:

df

students  roll_no
0    shyam        1
1      ram        4
2     hari        6

In [20]:
df['roll_no']

0    1
1    4
2    6
Name: roll_no, dtype: int64

In [21]:

df

students  roll_no
0    shyam        1
1      ram        4
2     hari        6