In [59]:
import numpy as np
import pandas as pd

In [60]:
a = np.arange(10, 20)

read_df = pd.read_csv("machine-readable-business-employment-data-sep-2024-quarter.csv")

In [61]:
np.sum(a)

np.int64(145)

In [62]:
np.sum

<function sum at 0x721392adea70>

In [63]:
np.mean(a)

np.float64(14.5)

In [64]:
np.mean

<function mean at 0x721391f04c70>

In [65]:
np.mean(a)

np.float64(14.5)

In [66]:
np.max(a)

np.int64(19)

In [67]:
np.min(a)

np.int64(10)

In [68]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [69]:
a[a<15]

array([10, 11, 12, 13, 14])

In [70]:
a = np.arange(0, 5)
b = np.arange(5, 10)
c = np.arange(10, 15)


print(a.size)
print(b.size)
c.size

5
5


5

In [71]:
data_columns = {"length":a ,"breadth":b, "width":c}

In [72]:
df = pd.DataFrame(data=data_columns)

In [73]:
df

length  breadth  width
0       0        5     10
1       1        6     11
2       2        7     12
3       3        8     13
4       4        9     14

In [74]:
df['breadth']>8

0    False
1    False
2    False
3    False
4     True
Name: breadth, dtype: bool

In [75]:
df['breadth']>=8

0    False
1    False
2    False
3     True
4     True
Name: breadth, dtype: bool

In [76]:
df['width'] = np.random.randint(0, 100, 5)

In [77]:
df

length  breadth  width
0       0        5     36
1       1        6     16
2       2        7     22
3       3        8     90
4       4        9     12

In [78]:
df.sort_values(by="width", ascending=True)

length  breadth  width
4       4        9     12
1       1        6     16
2       2        7     22
0       0        5     36
3       3        8     90

In [79]:
d, e, f = (np.random.randint(0,100,5), np.random.randint(0,100,5), np.random.randint(0,100,5))

In [80]:
df_2 = pd.DataFrame(data={"volume":d, "cubic_volume":e, "spacetime":f})

In [81]:
df_2

volume  cubic_volume  spacetime
0      50            49         86
1      31            49          8
2      32            58         74
3      44            94         78
4      15            64         18

In [82]:
another_df = pd.concat([df, df_2], axis=1)

In [83]:
another_df 

length  breadth  width  volume  cubic_volume  spacetime
0       0        5     36      50            49         86
1       1        6     16      31            49          8
2       2        7     22      32            58         74
3       3        8     90      44            94         78
4       4        9     12      15            64         18

In [85]:
df[0]

KeyError: 0

In [87]:
df

length  breadth  width
0       0        5     36
1       1        6     16
2       2        7     22
3       3        8     90
4       4        9     12

In [86]:
df.iloc[1]

length      1
breadth     6
width      16
Name: 1, dtype: int64

In [88]:
y = df['width']

In [89]:
y

0    36
1    16
2    22
3    90
4    12
Name: width, dtype: int64

In [94]:
df.iloc[3:5, 2]

3    90
4    12
Name: width, dtype: int64

In [95]:
arr = np.array([1,2,3])

In [96]:
arr

array([1, 2, 3])

In [97]:
another_df

length  breadth  width  volume  cubic_volume  spacetime
0       0        5     36      50            49         86
1       1        6     16      31            49          8
2       2        7     22      32            58         74
3       3        8     90      44            94         78
4       4        9     12      15            64         18

In [99]:
another_df.loc[0]

length           0
breadth          5
width           36
volume          50
cubic_volume    49
spacetime       86
Name: 0, dtype: int64

In [100]:

another_df.groupby("width").mean()

length  breadth  volume  cubic_volume  spacetime
width                                                  
12        4.0      9.0    15.0          64.0       18.0
16        1.0      6.0    31.0          49.0        8.0
22        2.0      7.0    32.0          58.0       74.0
36        0.0      5.0    50.0          49.0       86.0
90        3.0      8.0    44.0          94.0       78.0

In [103]:
another_df.groupby("volume").mean()

length  breadth  width  cubic_volume  spacetime
volume                                                 
15         4.0      9.0   12.0          64.0       18.0
31         1.0      6.0   16.0          49.0        8.0
32         2.0      7.0   22.0          58.0       74.0
44         3.0      8.0   90.0          94.0       78.0
50         0.0      5.0   36.0          49.0       86.0

In [104]:
df.isnull()

length  breadth  width
0   False    False  False
1   False    False  False
2   False    False  False
3   False    False  False
4   False    False  False

In [105]:
df.fillna(0)

length  breadth  width
0       0        5     36
1       1        6     16
2       2        7     22
3       3        8     90
4       4        9     12

In [107]:
df

length  breadth  width
0       0        5     36
1       1        6     16
2       2        7     22
3       3        8     90
4       4        9     12

In [106]:
df.dropna()

length  breadth  width
0       0        5     36
1       1        6     16
2       2        7     22
3       3        8     90
4       4        9     12